FROM python:3.7-slim

RUN apt-get update
RUN apt-get install -y --no-install-recommends \
	libgomp1

RUN pip install cython==0.29.12
RUN pip install pandas==0.25.0
RUN pip install scikit-learn==0.21.2
RUN pip install sortedcollections==1.1.2
RUN pip install pickleshare==0.7.5
RUN pip install google-cloud-bigquery==1.20.0
RUN pip install pyarrow==0.14.1
RUN pip install s3fs==0.2.0
RUN pip install xgboost==0.90

